name: adv_camera
description: An advanced camera with focus (with focus rectangle) and zoom feature.
version: 1.3.1+1
homepage: https://github.com/ricnaaru/adv_camera

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ric.adv_camera
        pluginClass: AdvCameraPlugin
      ios:
        pluginClass: AdvCameraPlugin